[package]
name = "cmake_gen"
version = "0.1.0"
authors = ["Gleb Kolobkov <gleyba.k@gmail.com>"]
edition = "2018"

[dependencies]
pico-args = "0.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"